/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PingerForIP;

import Target.University.AinShams;
import java.awt.Color;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.ColorSelectionModel;

/**
 *
 * @author Administrator
 */
public class PingerForIPJFrame extends javax.swing.JFrame {
boolean network=false,redexterna;
private AinShams Shams=new AinShams();
 ThreadManager Manage=new ThreadManager();
       
       
       
       
       
       
       
       
       /**
     * Creates new form PingerForIPJFrame
     */
    public PingerForIPJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPing = new javax.swing.JButton();
        jLabelAgriculture = new javax.swing.JLabel();
        jTextFieldAgriculture = new javax.swing.JTextField();
        jLabelAlson = new javax.swing.JLabel();
        jLabelArts = new javax.swing.JLabel();
        jLabelChildhood = new javax.swing.JLabel();
        jLabelAsnan = new javax.swing.JLabel();
        jLabelCommerceL3 = new javax.swing.JLabel();
        jLabelComputers = new javax.swing.JLabel();
        jLabelEngL3 = new javax.swing.JLabel();
        jLabelGirls = new javax.swing.JLabel();
        jLabelGuestHouse = new javax.swing.JLabel();
        jLabelHospital = new javax.swing.JLabel();
        jLabelEducation = new javax.swing.JLabel();
        jTextFieldAlson = new javax.swing.JTextField();
        jTextFieldArts = new javax.swing.JTextField();
        jTextFieldAsnan = new javax.swing.JTextField();
        jTextFieldChildhood = new javax.swing.JTextField();
        jTextFieldCommerceL3 = new javax.swing.JTextField();
        jTextFieldComputers = new javax.swing.JTextField();
        jTextFieldEducation = new javax.swing.JTextField();
        jTextFieldEngL3 = new javax.swing.JTextField();
        jTextFieldGirls = new javax.swing.JTextField();
        jTextFieldGuestHouse = new javax.swing.JTextField();
        jTextFieldHospital = new javax.swing.JTextField();
        jLabelOldManagement = new javax.swing.JLabel();
        jTextFieldScienceL3 = new javax.swing.JTextField();
        jLabelNewManagement = new javax.swing.JLabel();
        jTextFieldSpecificEducation = new javax.swing.JTextField();
        jLabelMedicalL3 = new javax.swing.JLabel();
        jTextFieldPharmacy = new javax.swing.JTextField();
        jTextFieldScienceDevelopment = new javax.swing.JTextField();
        jLabelMadina = new javax.swing.JLabel();
        jLabelLibrary = new javax.swing.JLabel();
        jLabelPharmacy = new javax.swing.JLabel();
        jLabelOptical = new javax.swing.JLabel();
        jLabelScienceDevelopment = new javax.swing.JLabel();
        jLabelScienceL3 = new javax.swing.JLabel();
        jLabelSpecificEducation = new javax.swing.JLabel();
        jLabelPalace = new javax.swing.JLabel();
        jTextFieldLibrary = new javax.swing.JTextField();
        jTextFieldMadina = new javax.swing.JTextField();
        jTextFieldMedicalL3 = new javax.swing.JTextField();
        jTextFieldNewManagement = new javax.swing.JTextField();
        jLabelLaws = new javax.swing.JLabel();
        jTextFieldOldManagement = new javax.swing.JTextField();
        jTextFieldPalace = new javax.swing.JTextField();
        jTextFieldOptical = new javax.swing.JTextField();
        jTextFieldLaws = new javax.swing.JTextField();
        jLabelLocation1 = new javax.swing.JLabel();
        jLabelStatus1 = new javax.swing.JLabel();
        jLabelLocation2 = new javax.swing.JLabel();
        jLabelStatus2 = new javax.swing.JLabel();
        jButtonStopPing = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonPingSingleIP = new javax.swing.JButton();
        jLabelDNS = new javax.swing.JLabel();
        jTextFieldMIS = new javax.swing.JTextField();
        jLabelMIS = new javax.swing.JLabel();
        jLabelPortal = new javax.swing.JLabel();
        jTextFieldFoundarySwitch = new javax.swing.JTextField();
        jTextFieldIPOQUE = new javax.swing.JTextField();
        jTextFieldUAC = new javax.swing.JTextField();
        jTextFieldSymanticWebGateway = new javax.swing.JTextField();
        jTextFieldFirewall = new javax.swing.JTextField();
        jTextFieldDNS = new javax.swing.JTextField();
        jLabelFoundarySwitch = new javax.swing.JLabel();
        jLabelGuestSymanticWebGateway = new javax.swing.JLabel();
        jLabelFirewall = new javax.swing.JLabel();
        jLabelIPOQUE = new javax.swing.JLabel();
        jLabelUAC = new javax.swing.JLabel();
        jTextFieldPortal = new javax.swing.JTextField();
        jLabelTMGServer = new javax.swing.JLabel();
        jTextFieldTMGServer = new javax.swing.JTextField();
        jTextFieldYahoo = new javax.swing.JTextField();
        jLabelYahoo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ain Shams Pinger - DAWOUD");

        jButtonPing.setText("Start Ping");
        jButtonPing.setToolTipText("Click to Start pinging");
        jButtonPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPingActionPerformed(evt);
            }
        });

        jLabelAgriculture.setText("Agriculture");

        jTextFieldAgriculture.setEditable(false);
        jTextFieldAgriculture.setText("Not Available");
        jTextFieldAgriculture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgricultureActionPerformed(evt);
            }
        });

        jLabelAlson.setText("Alson");

        jLabelArts.setText("Arts");

        jLabelChildhood.setText("Childhood");

        jLabelAsnan.setText("Asnan");

        jLabelCommerceL3.setText("Commerce L3");

        jLabelComputers.setText("Computers");

        jLabelEngL3.setText("Eng L3");

        jLabelGirls.setText("Girls");

        jLabelGuestHouse.setText("Guest House");

        jLabelHospital.setText("Hospital");

        jLabelEducation.setText("Education");

        jTextFieldAlson.setEditable(false);
        jTextFieldAlson.setText("Not Available");

        jTextFieldArts.setEditable(false);
        jTextFieldArts.setText("Not Available");

        jTextFieldAsnan.setEditable(false);
        jTextFieldAsnan.setText("Not Available");
        jTextFieldAsnan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAsnanActionPerformed(evt);
            }
        });

        jTextFieldChildhood.setEditable(false);
        jTextFieldChildhood.setText("Not Available");
        jTextFieldChildhood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChildhoodActionPerformed(evt);
            }
        });

        jTextFieldCommerceL3.setEditable(false);
        jTextFieldCommerceL3.setText("Not Available");
        jTextFieldCommerceL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCommerceL3ActionPerformed(evt);
            }
        });

        jTextFieldComputers.setEditable(false);
        jTextFieldComputers.setText("Not Available");

        jTextFieldEducation.setEditable(false);
        jTextFieldEducation.setText("Not Available");
        jTextFieldEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEducationActionPerformed(evt);
            }
        });

        jTextFieldEngL3.setEditable(false);
        jTextFieldEngL3.setText("Not Available");

        jTextFieldGirls.setEditable(false);
        jTextFieldGirls.setText("Not Available");
        jTextFieldGirls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGirlsActionPerformed(evt);
            }
        });

        jTextFieldGuestHouse.setEditable(false);
        jTextFieldGuestHouse.setText("Not Available");

        jTextFieldHospital.setEditable(false);
        jTextFieldHospital.setText("Not Available");

        jLabelOldManagement.setText("Old Management");

        jTextFieldScienceL3.setEditable(false);
        jTextFieldScienceL3.setText("Not Available");

        jLabelNewManagement.setText("New Management");

        jTextFieldSpecificEducation.setEditable(false);
        jTextFieldSpecificEducation.setText("Not Available");

        jLabelMedicalL3.setText("Medical L3");

        jTextFieldPharmacy.setEditable(false);
        jTextFieldPharmacy.setText("Not Available");

        jTextFieldScienceDevelopment.setEditable(false);
        jTextFieldScienceDevelopment.setText("Not Available");
        jTextFieldScienceDevelopment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldScienceDevelopmentActionPerformed(evt);
            }
        });

        jLabelMadina.setText("Madina");

        jLabelLibrary.setText("Library");

        jLabelPharmacy.setText("Pharmacy");

        jLabelOptical.setText("Optical");

        jLabelScienceDevelopment.setText("Science Development");

        jLabelScienceL3.setText("Science L3");

        jLabelSpecificEducation.setText("Specific Education");

        jLabelPalace.setText("Palace");

        jTextFieldLibrary.setEditable(false);
        jTextFieldLibrary.setText("Not Available");
        jTextFieldLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLibraryActionPerformed(evt);
            }
        });

        jTextFieldMadina.setEditable(false);
        jTextFieldMadina.setText("Not Available");

        jTextFieldMedicalL3.setEditable(false);
        jTextFieldMedicalL3.setText("Not Available");

        jTextFieldNewManagement.setEditable(false);
        jTextFieldNewManagement.setText("Not Available");
        jTextFieldNewManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewManagementActionPerformed(evt);
            }
        });

        jLabelLaws.setText("Laws");

        jTextFieldOldManagement.setEditable(false);
        jTextFieldOldManagement.setText("Not Available");

        jTextFieldPalace.setEditable(false);
        jTextFieldPalace.setText("Not Available");
        jTextFieldPalace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPalaceActionPerformed(evt);
            }
        });

        jTextFieldOptical.setEditable(false);
        jTextFieldOptical.setText("Not Available");
        jTextFieldOptical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOpticalActionPerformed(evt);
            }
        });

        jTextFieldLaws.setEditable(false);
        jTextFieldLaws.setText("Not Available");
        jTextFieldLaws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLawsActionPerformed(evt);
            }
        });

        jLabelLocation1.setText("Location");
        jLabelLocation1.setName("JLabelLocation1"); // NOI18N

        jLabelStatus1.setText("Status");

        jLabelLocation2.setText("Location");

        jLabelStatus2.setText("Status");

        jButtonStopPing.setText("Stop Ping");
        jButtonStopPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopPingActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonPingSingleIP.setText("Ping Single IP");
        jButtonPingSingleIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPingSingleIPActionPerformed(evt);
            }
        });

        jLabelDNS.setText("DNS");

        jTextFieldMIS.setEditable(false);
        jTextFieldMIS.setText("Not Available");
        jTextFieldMIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMISActionPerformed(evt);
            }
        });

        jLabelMIS.setText("MIS");

        jLabelPortal.setText("Portal");

        jTextFieldFoundarySwitch.setEditable(false);
        jTextFieldFoundarySwitch.setText("Not Available");
        jTextFieldFoundarySwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFoundarySwitchActionPerformed(evt);
            }
        });

        jTextFieldIPOQUE.setEditable(false);
        jTextFieldIPOQUE.setText("Not Available");

        jTextFieldUAC.setEditable(false);
        jTextFieldUAC.setText("Not Available");
        jTextFieldUAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUACActionPerformed(evt);
            }
        });

        jTextFieldSymanticWebGateway.setEditable(false);
        jTextFieldSymanticWebGateway.setText("Not Available");

        jTextFieldFirewall.setEditable(false);
        jTextFieldFirewall.setText("Not Available");

        jTextFieldDNS.setEditable(false);
        jTextFieldDNS.setText("Not Available");

        jLabelFoundarySwitch.setText("Foundary Switch");

        jLabelGuestSymanticWebGateway.setText("SymanticWebGate.");

        jLabelFirewall.setText("Firewall");

        jLabelIPOQUE.setText("IPOQUE");

        jLabelUAC.setText("U A C");

        jTextFieldPortal.setEditable(false);
        jTextFieldPortal.setText("Not Available");
        jTextFieldPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortalActionPerformed(evt);
            }
        });

        jLabelTMGServer.setText("TMG Server");

        jTextFieldTMGServer.setEditable(false);
        jTextFieldTMGServer.setText("Not Available");

        jTextFieldYahoo.setEditable(false);
        jTextFieldYahoo.setText("Not Available");

        jLabelYahoo.setText("Yahoo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCommerceL3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelComputers, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldComputers)
                                    .addComponent(jTextFieldCommerceL3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAgriculture, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAgriculture))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAlson, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAlson))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelArts, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldArts))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelChildhood, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldChildhood))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAsnan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAsnan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGirls, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGirls))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGuestHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGuestHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEducation))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEngL3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEngL3)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelLaws, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                        .addGap(63, 63, 63)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLaws, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLibrary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMedicalL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNewManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNewManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMedicalL3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMadina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPalace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOptical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOldManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOldManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldOptical, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPalace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPharmacy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSpecificEducation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelScienceL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelScienceDevelopment, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldScienceDevelopment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldScienceL3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSpecificEducation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLocation2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelStatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonPing)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStopPing)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonPingSingleIP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUAC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUAC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGuestSymanticWebGateway, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSymanticWebGateway, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFoundarySwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFoundarySwitch))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIPOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIPOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFirewall, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldFirewall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPortal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPortal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelMIS, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTMGServer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTMGServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabelYahoo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldYahoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLocation1)
                            .addComponent(jLabelStatus1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLocation2)
                            .addComponent(jLabelStatus2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLaws, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLaws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMadina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMadina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMedicalL3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMedicalL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNewManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNewManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOldManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOldManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOptical, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOptical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPalace, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPalace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelScienceDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldScienceDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelScienceL3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldScienceL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSpecificEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSpecificEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAgriculture, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAgriculture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlson, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAlson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelArts, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldArts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAsnan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAsnan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChildhood, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldChildhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCommerceL3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCommerceL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelComputers, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldComputers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEngL3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEngL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGirls, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGirls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGuestHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGuestHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPortal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPortal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDNS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMIS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFirewall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFirewall, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFoundarySwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFoundarySwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIPOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIPOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUAC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGuestSymanticWebGateway, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSymanticWebGateway, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldYahoo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYahoo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTMGServer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTMGServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPing)
                    .addComponent(jButtonStopPing)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonPingSingleIP))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPingActionPerformed

       
        
       
        Manage.StartThreads();
        //Manage.StopThreads();
        
//        try   
//            { 
//                
//                
//                
//                //start modification
//                
//                //jTextFieldAlson.setText();
//                
//                //PingTaskRunnable Ping=new PingTaskRunnable(Shams.getCommerceL3().GetName(), Shams.getCommerceL3().GetIPAddress());
//               
//                                
//                
//                // end modification
//                InetAddress ADDRESS =InetAddress.getByName(Shams.getOptical().GetIPAddress());  
//                redexterna=ADDRESS.isReachable(2000);
//                System.out.println("Value is" + redexterna);  
//                Thread.sleep(3000);  
//            } catch (UnknownHostException e4)   
//            {  
//                // TODO Auto-generated catch block  
//                e4.printStackTrace();  
//            } catch (IOException e4) {  
//                // TODO Auto-generated catch block  
//                e4.printStackTrace();  
//            } 
//            catch (InterruptedException e) {  
//                // TODO Auto-generated catch block  
//                e.printStackTrace();  
//            } 
//            String StatusString=String.valueOf(redexterna);
//            jTextFieldAgriculture.setText(StatusString);
//            jTextFieldAgriculture.setBackground(Color.RED);
           

    }//GEN-LAST:event_jButtonPingActionPerformed

    
    private void jTextFieldAgricultureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgricultureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgricultureActionPerformed

    private void jTextFieldAsnanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAsnanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAsnanActionPerformed

    private void jTextFieldChildhoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChildhoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChildhoodActionPerformed

    private void jTextFieldCommerceL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCommerceL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCommerceL3ActionPerformed

    private void jTextFieldEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEducationActionPerformed

    private void jTextFieldLawsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLawsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLawsActionPerformed

    private void jTextFieldLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLibraryActionPerformed

    private void jTextFieldNewManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewManagementActionPerformed

    private void jTextFieldOpticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOpticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOpticalActionPerformed

    private void jTextFieldScienceDevelopmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldScienceDevelopmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldScienceDevelopmentActionPerformed

    private void jTextFieldPalaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPalaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPalaceActionPerformed

    private void jTextFieldGirlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGirlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGirlsActionPerformed

    private void jButtonStopPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopPingActionPerformed
        // TODO add your handling code here:
        Manage.StopThreads();
        
    }//GEN-LAST:event_jButtonStopPingActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        Manage.StopThreads();
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonPingSingleIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPingSingleIPActionPerformed
        // TODO add your handling code here:
        
        
       //String IP=JOptionPane.showInputDialog(this , "Please Enter IP Address");
       Manage.StartSingleThread();
       
       
    }//GEN-LAST:event_jButtonPingSingleIPActionPerformed

    private void jTextFieldMISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMISActionPerformed

    private void jTextFieldFoundarySwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFoundarySwitchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFoundarySwitchActionPerformed

    private void jTextFieldUACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUACActionPerformed

    private void jTextFieldPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPortalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PingerForIPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PingerForIPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PingerForIPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PingerForIPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PingerForIPJFrame().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPing;
    private javax.swing.JButton jButtonPingSingleIP;
    private javax.swing.JButton jButtonStopPing;
    private javax.swing.JLabel jLabelAgriculture;
    private javax.swing.JLabel jLabelAlson;
    private javax.swing.JLabel jLabelArts;
    private javax.swing.JLabel jLabelAsnan;
    private javax.swing.JLabel jLabelChildhood;
    private javax.swing.JLabel jLabelCommerceL3;
    private javax.swing.JLabel jLabelComputers;
    private javax.swing.JLabel jLabelDNS;
    private javax.swing.JLabel jLabelEducation;
    private javax.swing.JLabel jLabelEngL3;
    private javax.swing.JLabel jLabelFirewall;
    private javax.swing.JLabel jLabelFoundarySwitch;
    private javax.swing.JLabel jLabelGirls;
    private javax.swing.JLabel jLabelGuestHouse;
    private javax.swing.JLabel jLabelGuestSymanticWebGateway;
    private javax.swing.JLabel jLabelHospital;
    private javax.swing.JLabel jLabelIPOQUE;
    private javax.swing.JLabel jLabelLaws;
    private javax.swing.JLabel jLabelLibrary;
    private javax.swing.JLabel jLabelLocation1;
    private javax.swing.JLabel jLabelLocation2;
    private javax.swing.JLabel jLabelMIS;
    private javax.swing.JLabel jLabelMadina;
    private javax.swing.JLabel jLabelMedicalL3;
    private javax.swing.JLabel jLabelNewManagement;
    private javax.swing.JLabel jLabelOldManagement;
    private javax.swing.JLabel jLabelOptical;
    private javax.swing.JLabel jLabelPalace;
    private javax.swing.JLabel jLabelPharmacy;
    private javax.swing.JLabel jLabelPortal;
    private javax.swing.JLabel jLabelScienceDevelopment;
    private javax.swing.JLabel jLabelScienceL3;
    private javax.swing.JLabel jLabelSpecificEducation;
    private javax.swing.JLabel jLabelStatus1;
    private javax.swing.JLabel jLabelStatus2;
    private javax.swing.JLabel jLabelTMGServer;
    private javax.swing.JLabel jLabelUAC;
    private javax.swing.JLabel jLabelYahoo;
    public static javax.swing.JTextField jTextFieldAgriculture;
    public static javax.swing.JTextField jTextFieldAlson;
    public static javax.swing.JTextField jTextFieldArts;
    public static javax.swing.JTextField jTextFieldAsnan;
    public static javax.swing.JTextField jTextFieldChildhood;
    public static javax.swing.JTextField jTextFieldCommerceL3;
    public static javax.swing.JTextField jTextFieldComputers;
    public static javax.swing.JTextField jTextFieldDNS;
    public static javax.swing.JTextField jTextFieldEducation;
    public static javax.swing.JTextField jTextFieldEngL3;
    public static javax.swing.JTextField jTextFieldFirewall;
    public static javax.swing.JTextField jTextFieldFoundarySwitch;
    public static javax.swing.JTextField jTextFieldGirls;
    public static javax.swing.JTextField jTextFieldGuestHouse;
    public static javax.swing.JTextField jTextFieldHospital;
    public static javax.swing.JTextField jTextFieldIPOQUE;
    public static javax.swing.JTextField jTextFieldLaws;
    public static javax.swing.JTextField jTextFieldLibrary;
    public static javax.swing.JTextField jTextFieldMIS;
    public static javax.swing.JTextField jTextFieldMadina;
    public static javax.swing.JTextField jTextFieldMedicalL3;
    public static javax.swing.JTextField jTextFieldNewManagement;
    public static javax.swing.JTextField jTextFieldOldManagement;
    public static javax.swing.JTextField jTextFieldOptical;
    public static javax.swing.JTextField jTextFieldPalace;
    public static javax.swing.JTextField jTextFieldPharmacy;
    public static javax.swing.JTextField jTextFieldPortal;
    public static javax.swing.JTextField jTextFieldScienceDevelopment;
    public static javax.swing.JTextField jTextFieldScienceL3;
    public static javax.swing.JTextField jTextFieldSpecificEducation;
    public static javax.swing.JTextField jTextFieldSymanticWebGateway;
    public static javax.swing.JTextField jTextFieldTMGServer;
    public static javax.swing.JTextField jTextFieldUAC;
    public static javax.swing.JTextField jTextFieldYahoo;
    // End of variables declaration//GEN-END:variables
}
